### ISSUE TITLE
Network Serialization Examples Fail

### ISSUE THREAD

**Issue by seanmkauffman** [liflab/beepbeep-3-examples#7] opened 2020-05-26 22:14 UTC
Running either PushLocalSerialize, or the split version using PushMachineA and PushMachineB, the same error is encountered when an attempt is made to push an object.
I have been unable to debug the error in detail, but it seems to be related to serialization and deserialization.  The PushLocalSimple example runs without issue.  I have not tried a different JDK to see if that is the cause.

 $ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (IcedTea 3.15.0) (Gentoo icedtea-3.15.0)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

First, the error from PushLocalSerialize:
```
Exception in thread "main" ca.uqac.lif.cep.Pushable$PushableException: ca.uqac.lif.cep.ProcessorException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:12144/push
	at ca.uqac.lif.cep.SynchronousProcessor$InputPushable.push(SynchronousProcessor.java:198)
	at ca.uqac.lif.cep.UniformProcessor$UnaryPushable.push(UniformProcessor.java:188)
	at network.httppush.PushLocalSerialize.main(PushLocalSerialize.java:136)
Caused by: ca.uqac.lif.cep.ProcessorException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:12144/push
	at ca.uqac.lif.cep.http.HttpUpstreamGateway.compute(HttpUpstreamGateway.java:139)
	at ca.uqac.lif.cep.SynchronousProcessor$InputPushable.push(SynchronousProcessor.java:194)
	... 2 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:12144/push
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at ca.uqac.lif.cep.http.HttpGateway.sendPost(HttpGateway.java:91)
	at ca.uqac.lif.cep.http.HttpUpstreamGateway.compute(HttpUpstreamGateway.java:124)
	... 3 more
```

Then, the error from running PushMachineA/B with 20202 as the port.
```
Exception in thread "main" ca.uqac.lif.cep.Pushable$PushableException: ca.uqac.lif.cep.ProcessorException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:20202/push
	at ca.uqac.lif.cep.SynchronousProcessor$InputPushable.push(SynchronousProcessor.java:198)
	at ca.uqac.lif.cep.UniformProcessor$UnaryPushable.push(UniformProcessor.java:188)
	at ca.uqac.lif.cep.UniformProcessor$UnaryPushable.pushFast(UniformProcessor.java:195)
	at ca.uqac.lif.cep.tmf.Source.push(Source.java:77)
	at network.httppush.PushMachineA.main(PushMachineA.java:77)
Caused by: ca.uqac.lif.cep.ProcessorException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:20202/push
	at ca.uqac.lif.cep.http.HttpUpstreamGateway.compute(HttpUpstreamGateway.java:139)
	at ca.uqac.lif.cep.SynchronousProcessor$InputPushable.push(SynchronousProcessor.java:194)
	... 4 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:20202/push
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at ca.uqac.lif.cep.http.HttpGateway.sendPost(HttpGateway.java:91)
	at ca.uqac.lif.cep.http.HttpUpstreamGateway.compute(HttpUpstreamGateway.java:124)
	... 5 more
```

**Comment by sylvainhalle** [comment] 2020-05-27 14:01
Thanks for notifying me! I have the same error and I am investigating the problem.

**Comment by sylvainhalle** [comment] 2020-05-27 14:08
Boils down to this exception inside `HttpDownstreamGateway`:

```
java.lang.IllegalArgumentException: Can not set int field network.CompoundObject.a to java.lang.Long
```

**Comment by sylvainhalle** [comment] 2020-05-27 14:32
Not a BeepBeep error, actually caused by: https://github.com/sylvainhalle/Azrael/issues/8

**Comment by sylvainhalle** [comment] 2020-05-27 16:10
The bug was fixed in `json-lif`, which in turn triggered a new release of Azrael, which in turn required a rebuild of the pre-compiled palettes `Serialization` and `Json`. If you update these two palettes to the latest version (https://github.com/liflab/beepbeep-3-palettes/releases/tag/v20200527), the problem should be fixed (I just tested it). Please let me know if you have any further issues.

**Comment by seanmkauffman** [comment] 2020-05-27 19:20
I don't know if it's related, but now, using the new libraries from the release you linked, I see two copies of each Object received when using the http palette.  Even just running PushLocalSimple outputs "foo,foo,bar,bar,".  The serialization problem seems to be fixed, though.

  [I went ahead and opened a separate issue to track this.](https://github.com/liflab/beepbeep-3-examples/issues/8)

**Comment by sylvainhalle** [comment] 2020-05-27 21:28
I don't think it's related, but it's a bug nonetheless. I'll look into that!

**Comment by sylvainhalle** [comment] 2020-05-27 21:28
Just saw you opened a separate issue

**Closed as completed by sylvainhalle** 2020-05-27 21:28 UTC
Labels: bug
